### PR TITLE
Document steps to compile on Mac

### PR DESCRIPTION
**Pull request by bruno-garcia**
For the most part it seems to compile fine on a mac:

```
...
-- Installing: /Users/bruno/git/sentry-godot/sentry-native/install/lib/libcrashpad_tools.a
-- Installing: /Users/bruno/git/sentry-godot/sentry-native/install/lib/libcrashpad_handler_lib.a
-- Installing: /Users/bruno/git/sentry-godot/sentry-native/install/bin/crashpad_handler
Copy("project/addons/sentrysdk/bin/crashpad_handler", "sentry-native/install/bin/crashpad_handler")
Linking Shared Library project/addons/sentrysdk/bin/libsentrysdk.macos.editor.framework/libsentrysdk.macos.editor ...
ld: library 'crashpad_compat' not found
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [project/addons/sentrysdk/bin/libsentrysdk.macos.editor.framework/libsentrysdk.macos.editor] Error 1
scons: building terminated because of errors.
```

Except it failed on some crashpad related issue

```
> ls project/addons/sentrysdk/bi
crashpad_handler                        
libsentrysdk.macos.editor.framework     
sentrysdk.gdextension
```

Then with `scons target=template_release debug_symbols=yes` it also got mostly done:

```
[ 65%] Built target crashpad_client
[ 80%] Built target crashpad_snapshot
[ 93%] Built target crashpad_minidump
[ 98%] Built target crashpad_handler_lib
[100%] Built target crashpad_handler
-- Up-to-date: /Users/bruno/git/sentry-godot/sentry-native/install/lib/cmake/sentry/sentry_crashpad-targets.cmake
-- Up-to-date: /Users/bruno/git/sentry-godot/sentry-native/install/lib/cmake/sentry/sentry_crashpad-targets-relwithdebinfo.cmake
-- Installing: /Users/bruno/git/sentry-godot/sentry-native/install/lib/libsentry.a
-- Up-to-date: /Users/bruno/git/sentry-godot/sentry-native/install/include/sentry.h
-- Up-to-date: /Users/bruno/git/sentry-godot/sentry-native/install/lib/cmake/sentry/sentry-targets.cmake
-- Up-to-date: /Users/bruno/git/sentry-godot/sentry-native/install/lib/cmake/sentry/sentry-targets-relwithdebinfo.cmake
-- Up-to-date: /Users/bruno/git/sentry-godot/sentry-native/install/lib/cmake/sentry/sentry-config.cmake
-- Up-to-date: /Users/bruno/git/sentry-godot/sentry-native/install/lib/cmake/sentry/sentry-config-version.cmake
-- Installing: /Users/bruno/git/sentry-godot/sentry-native/install/lib/libcrashpad_minidump.a
-- Installing: /Users/bruno/git/sentry-godot/sentry-native/install/lib/libcrashpad_snapshot.a
-- Installing: /Users/bruno/git/sentry-godot/sentry-native/install/lib/libcrashpad_util.a
-- Installing: /Users/bruno/git/sentry-godot/sentry-native/install/lib/libmini_chromium.a
-- Installing: /Users/bruno/git/sentry-godot/sentry-native/install/lib/libcrashpad_client.a
-- Installing: /Users/bruno/git/sentry-godot/sentry-native/install/lib/libcrashpad_tools.a
-- Installing: /Users/bruno/git/sentry-godot/sentry-native/install/lib/libcrashpad_handler_lib.a
-- Up-to-date: /Users/bruno/git/sentry-godot/sentry-native/install/bin/crashpad_handler
Copy("project/addons/sentrysdk/bin/crashpad_handler", "sentry-native/install/bin/crashpad_handler")
Linking Shared Library project/addons/sentrysdk/bin/libsentrysdk.macos.template_release.framework/libsentrysdk.macos.template_release ...
ld: library 'crashpad_compat' not found
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [project/addons/sentrysdk/bin/libsentrysdk.macos.template_release.framework/libsentrysdk.macos.template_release] Error 1
scons: building terminated because of errors.
```

### CODE REVIEW

**Comment by limbonaut** [comment]
Has it actually built the target `crashpad_compat`?
I don't see it being installed like here: https://github.com/getsentry/sentry-godot/actions/runs/11990307128/job/33427667882#step:5:1633

**Comment by bruno-garcia** [comment]
> Has it actually built the target `crashpad_compat`? I don't see it being installed like here: [getsentry/sentry-godot/actions/runs/11990307128/job/33427667882#step:5:1633](https://github.com/getsentry/sentry-godot/actions/runs/11990307128/job/33427667882#step:5:1633)

On this link I see 42 entries for that, including these:
image


On the Unreal package we have: https://github.com/search?q=repo%3Agetsentry%2Fsentry-unreal+crashpad_compat&type=code

**Comment by limbonaut** [comment]
Looks like `crashpad_compat` lib has a different definition on macOS:

https://github.com/getsentry/crashpad/blob/852f8fea9cbea7a63610b8c698f301bd1ba4b3cd/compat/CMakeLists.txt#L85-L94

It fails to link it, and perhaps the build shouldn't try to link it on mac?

**Comment by bruno-garcia** [comment]
Looks like I have some commits from the CI branch I that was already merged to main, but show in the diff. Feel free to close the PR or take what's needed if that's easier then merging

**Comment by limbonaut** [comment]
Superseded by #33

**Pull request closed without merging**
